theme: jekyll-theme-time-machine
title: [Sushil Prasad]
description: [Technical Project Lead]
linkedin_url: https://www.linkedin.com/in/sushilprasad
resume_url: https://bit.ly/3ElLrxQ
show_resume: true

